### ISSUE TITLE
insert, update, delete, commit, rollback should report a 'number of documents affected'

### ISSUE THREAD

**Issue by andreasbaumann** [Eurospider/strusWebService#11]
As in a database. This helps users of the service to react properly.

**Comment by andreasbaumann** [comment]
Do we have support for this from the strus library?

**Comment by andreasbaumann** [comment]
Logical would be insert/update/delete giving us number of documents affected, begin/
rollback/commit are always 0. This is like for instance in a database like Postgresql and
easy to implement.

**Comment by patrickfrey** [comment]
There is support now in the strus core:

StorageTransactionInterface:
      virtual unsigned int nofDocumentsAffected() const=0;

**Comment by andreasbaumann** [comment]
We haev do adjust our model in the webservice a little bit: we cannot know on insert or
delete how many documents will be affected, only when we commit. In the implicit
commit case this also works.
