### ISSUE TITLE
Running out of memory while inserting on a 32-bit machine

### ISSUE THREAD

**Issue by andreasbaumann** [Eurospider/strusWebService#15]
```
2016-05-04 08:45:07; strusWebService, error: storage transaction with error: storage transaction with error: storage transaction with error: storage transaction with error: storage transaction with error: storage transaction with error: storage transaction with error: error in database transaction commit: database transaction with error: memory allocation error (master.cpp:73)
```

**Comment by andreasbaumann** [comment]
Looks like a memory leak, valgrindifying is the recommended treatment. :-)

**Comment by andreasbaumann** [comment]
https://gist.github.com/andreasbaumann/2114e35950cb626c1c513530efd2d15c

This cannot explain why we use more and more memory on a 32-bit machine (rather
LevelDB and it's way of using memory for mmapped files does).

**Comment by andreasbaumann** [comment]
Size of the collection: 100'000 XML documents, in total 2.3 GBytes, roughly 23 KBytes per
file.

**Comment by patrickfrey** [comment]
What storage options were used 
{
     max_open_files
     write_buffer_size
     block_size
}
?
These options with the commit size (number of documents in a transaction) control the memory usage. Were the default used ?

**Comment by andreasbaumann** [comment]
Currently hunting a bug whether the storage options are actually passed down from
the service down to the storage library.

**Comment by andreasbaumann** [comment]
Actually not commenting out the options in strusWebService.conf helped. :-)
